# Generated by Django 2.0 on 2017-12-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
