# Generated by Django 2.0 on 2018-01-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readyapp', '0002_usercredentials'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercredentials',
            table='user',
        ),
    ]
