# Generated by Django 2.0 on 2018-01-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readyapp', '0003_auto_20180103_1545'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercredentials',
            table='userdetails',
        ),
    ]
