# Generated by Django 2.0 on 2018-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_auto_20180221_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=10)),
                ('Maximum_Participants', models.IntegerField(max_length=3)),
                ('Room_Type', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
